/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProposalsRouteImport } from './routes/api/proposals'
import { Route as ApiProposalsGenerateRouteImport } from './routes/api/proposals.generate'
import { Route as ApiRfpAnalyzeRouteImport } from './routes/api/rfp.analyze'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProposalsRoute = ApiProposalsRouteImport.update({
  id: '/api/proposals',
  path: '/api/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProposalsGenerateRoute = ApiProposalsGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => ApiProposalsRoute,
} as any)
const ApiRfpAnalyzeRoute = ApiRfpAnalyzeRouteImport.update({
  id: '/api/rfp/analyze',
  path: '/api/rfp/analyze',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/proposals': typeof ApiProposalsRouteWithChildren
  '/api/proposals/generate': typeof ApiProposalsGenerateRoute
  '/api/rfp/analyze': typeof ApiRfpAnalyzeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/proposals': typeof ApiProposalsRouteWithChildren
  '/api/proposals/generate': typeof ApiProposalsGenerateRoute
  '/api/rfp/analyze': typeof ApiRfpAnalyzeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/proposals': typeof ApiProposalsRouteWithChildren
  '/api/proposals/generate': typeof ApiProposalsGenerateRoute
  '/api/rfp/analyze': typeof ApiRfpAnalyzeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/proposals' | '/api/proposals/generate' | '/api/rfp/analyze'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/proposals' | '/api/proposals/generate' | '/api/rfp/analyze'
  id:
    | '__root__'
    | '/'
    | '/api/proposals'
    | '/api/proposals/generate'
    | '/api/rfp/analyze'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiProposalsRoute: typeof ApiProposalsRouteWithChildren
  ApiRfpAnalyzeRoute: typeof ApiRfpAnalyzeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proposals': {
      id: '/api/proposals'
      path: '/api/proposals'
      fullPath: '/api/proposals'
      preLoaderRoute: typeof ApiProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proposals/generate': {
      id: '/api/proposals/generate'
      path: '/generate'
      fullPath: '/api/proposals/generate'
      preLoaderRoute: typeof ApiProposalsGenerateRouteImport
      parentRoute: typeof ApiProposalsRoute
    }
    '/api/rfp/analyze': {
      id: '/api/rfp/analyze'
      path: '/api/rfp/analyze'
      fullPath: '/api/rfp/analyze'
      preLoaderRoute: typeof ApiRfpAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiProposalsRouteChildren {
  ApiProposalsGenerateRoute: typeof ApiProposalsGenerateRoute
}

const ApiProposalsRouteChildren: ApiProposalsRouteChildren = {
  ApiProposalsGenerateRoute: ApiProposalsGenerateRoute,
}

const ApiProposalsRouteWithChildren = ApiProposalsRoute._addFileChildren(
  ApiProposalsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiProposalsRoute: ApiProposalsRouteWithChildren,
  ApiRfpAnalyzeRoute: ApiRfpAnalyzeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
